name = "sixpixie"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "USER_CONFIG"
id = "84956a7696c84c81847bf8f8e386d3f5"
preview_id = "f8ba993b370244cdb90dd58058628a52"

[vars]
GITHUB_REPO = "ovowod/sixpixie"
GITHUB_WORKFLOW_FILE = "notify.yml"
GITHUB_REF = "main"

# Secrets — set via `wrangler secret put`:
# DISCORD_BOT_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# SUBWAY_API_KEY
# GITHUB_TOKEN
